# Bilibili 去广告 8.13 (适配 iOS 15+)
# 移除开屏、推荐页广告、动态列表广告及视频页推荐广告
# 作者：app2smile
# 更新日期：2025-05-13


# 1. Bilibili JSON 类接口 (开屏、首页标签、推荐列表)
^https:\/\/app\.bilibili\.com\/x\/(v2\/(splash\/(list|show)|feed\/index\?)|resource\/show\/tab\/v2) url script-response-body https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-json.js

# 2. Bilibili ProtoBuf/gRPC 类接口 (视频详情页、动态列表)
# QX 会自动处理二进制正文，需确保脚本路径正确
^https?:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.(viewunite\.v1\.View\/View|dynamic\.v2\.Dynamic\/DynAll) url script-response-body https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-proto.js


hostname = app.bilibili.com, grpc.biliapi.net