# 酷安去广告
# 移除开屏、信息流广告、热搜及赞助卡片
# 适配自：RuCu6 & 可莉🅥
# 更新日期：2025-05-13

[rewrite_local]
# 热搜处理 (Map Local 替代)
^https:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch url reject-dict

# 酷安内容过滤脚本 (涵盖了原本所有的 JQ 逻辑)
^https:\/\/api\.coolapk\.com\/v6\/(feed\/(detail|replyList)|main\/(dataList|indexV8|init)|page\/dataList) url script-response-body https://raw.githubusercontent.com/luestr/ProxyResource/main/Tool/Coolapk/Coolapk_remove_ads.js

[mitm]
hostname = api.coolapk.com