#!name=飞猫管家去广告
#!desc=移除开屏 by @sliverkiss
#!icon=https://raw.githubusercontent.com/sliverkiss/QuantumultX/main/icon/fmgj.png

^https:\/\/app\.flymodem\.com\.cn\/Appapi\/Public\/welecome url reject
^https:\/\/app\.flymodem\.com\.cn\/appapi\/index\/alert_view url reject

hostname = app.flymodem.com.cn