# 飞客去广告
# 移除开屏广告、首页广告、板块广告、帖内广告和我的页面广告。
# 作者：可莉🅥
# 更新日期：2025-05-13

# URL Rewrite (Reject)
^https:\/\/www\.flyert\.com\.cn\/api\/mobile\/index\.php\?module=advis url reject-200

# Map Local 转换 (针对返回空 JSON 的处理)
^https:\/\/www\.flyert\.com\.cn\/api\/mobile\/index\.php\?module=vip_coupon url reject-dict
^https:\/\/www\.flyert\.com\.cn\/api\/mobile\/index\.php\?module=getdata url reject-dict

# Map Local 转换 (针对图片/GIF)
^https:\/\/ptf\.flyertrip\.com\/static\/img\/common\/ic_plate_mine_button\.png url reject-img

# Script (重写脚本)
^https:\/\/www\.flyert\.com\.cn\/api\/mobile\/index\.php\?version=5 url script-response-body https://kelee.one/Resource/JavaScript/FlyerTea/FlyerTea_remove_ads.js
^https:\/\/www\.flyert\.com\.cn\/api\/mobile\/index\.php\?module=plugin&id=k_misign:sign url script-response-body https://kelee.one/Resource/JavaScript/FlyerTea/FlyerTea_remove_ads.js

hostname = www.flyert.com.cn, ptf.flyertrip.com