# 京东去广告
# 移除开屏广告，精简我的页面及推广。
# 作者：RuCu6, Maasea
# 更新日期：2025-05-13

# 拦截京东诊断/调试接口
^http:\/\/\w{32}\.jddebug\.com\/diagnose\? url reject

# --- Map Local (本地响应) ---
# 屏蔽搜索框热词、推荐位等
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(searchBoxWord|stationPullService|uniformRecommend[06]) url reject-dict

# --- Script (核心重写脚本) ---
# 涵盖了 basicConfig 的修改（禁用 HTTPDNS 等）以及 start、personinfo 等页面的精简
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(basicConfig|deliverLayer|getTabHomeInfo|myOrderInfo|orderTrackBusiness|personinfoBusiness|start|welcomeHome) url script-response-body https://kelee.one/Resource/JavaScript/JD/JD_remove_ads.js

# 比价
^https?:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html url script-response-body https://raw.githubusercontent.com/wf021325/qx/master/js/jd_price.js
^https?:\/\/apapia-sqk-weblogic\.manmanbuy\.com\/baoliao\/center\/menu$ url script-request-body https://raw.githubusercontent.com/wf021325/qx/master/js/jd_price.js

hostname = api.m.jd.com, in.m.jd.com, apapia-sqk-weblogic.manmanbuy.com