#!name=小红书去广告
#!desc=过滤信息流推广，移除图片及视频水印，如有异常请清缓存
#!author=RuCu6,fmz200
#!icon=https://raw.githubusercontent.com/luestr/IconResource/main/App_icon/120px/RedPaper.png
#!tag=去广告
#!homepage=https://hub.kelee.one
#!date=2026-02-22

# QUIC 阻止
^https?:\/\/.*\.xiaohongshu\.com url reject-200

# Map Local
^https:\/\/ci\.xiaohongshu\.com\/system_config\/watermark url 200
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/surprisebox\/(?:get_style|open|submit_action) url 200 data-body {}
^https:\/\/www\.xiaohongshu\.com\/api\/marketing\/box\/trigger\? url 200 data-body {}
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v2\/guide\/user_banner|v3\/note\/guide) url 200 data-body {}
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/(?:v1\/ads\/resource|v2\/hey\/\w+\/hey_gallery) url 200 data-body {}

# 去水印脚本
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/note\/(?:imagefeed|live_photo\/save) url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# UI配置
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/system\/service\/ui\/config\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 开屏广告
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v1\/system_service\/config\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/system_service\/splash_config url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 详情页组件
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v2\/(?:note\/widgets|user\/followings\/followfeed) url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 信息流广告
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v4\/followfeed\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js
^https:\/\/(?:edith|rec)\.xiaohongshu\.com\/api\/sns\/v6\/homefeed\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 推荐用户
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v5\/recommend\/user\/follow_recommend\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 评论区
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v1\/interaction\/comment\/video\/download|v5\/note\/comment\/list) url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 图片视频水印
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/(?:v2\/note\/feed|v3\/note\/videofeed) url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 搜索页广告
^https:\/\/(?:edith|so)\.xiaohongshu\.com\/api\/sns\/v10\/search\/notes\? url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js

# 视频水印
^https:\/\/(?:edith|rec|www)\.xiaohongshu\.com\/api\/sns\/(?:v4\/note\/videofeed|v10\/note\/video\/save) url script-response-body https://kelee.one/Resource/JavaScript/RedPaper/RedPaper_remove_ads.js


hostname = ci.xiaohongshu.com, edith.xiaohongshu.com, rec.xiaohongshu.com, so.xiaohongshu.com, www.xiaohongshu.com